lint:
  stage: test
  image: python:3.11
  cache:
    key: "${CI_COMMIT_REF_SLUG}-precommit"
    paths:
      - .pre-commit-cache/

  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install pre-commit

  script:
    - pre-commit run --all-files

  only:
    - master

  interruptible: true
